CREATE schema IF NOT EXISTS sitestatdb;
SET search_path TO sitestatdb;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA sitestatdb;
CREATE TABLE IF NOT EXISTS sitestatdb.events(
  event_id UUID PRIMARY KEY NOT NULL UNIQUE,
  user_id VARCHAR(256) NOT NULL,
  page_id VARCHAR(256) NOT NULL,
  DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE schema IF NOT EXISTS sitestattestdb;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA sitestattestdb;
CREATE TABLE IF NOT EXISTS sitestattestdb.events(
  event_id UUID PRIMARY KEY NOT NULL UNIQUE,
  user_id VARCHAR(256) NOT NULL,
  page_id VARCHAR(256) NOT NULL,
  DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
